/*
Avatar Api v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package avatarv1

import (
	"encoding/json"
)

// checks if the RobloxWebResponsesAvatarScaleModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RobloxWebResponsesAvatarScaleModel{}

// RobloxWebResponsesAvatarScaleModel struct for RobloxWebResponsesAvatarScaleModel
type RobloxWebResponsesAvatarScaleModel struct {
	Height *float64 `json:"height,omitempty"`
	Width *float64 `json:"width,omitempty"`
	Head *float64 `json:"head,omitempty"`
	Depth *float64 `json:"depth,omitempty"`
	Proportion *float64 `json:"proportion,omitempty"`
	BodyType *float64 `json:"bodyType,omitempty"`
}

// NewRobloxWebResponsesAvatarScaleModel instantiates a new RobloxWebResponsesAvatarScaleModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRobloxWebResponsesAvatarScaleModel() *RobloxWebResponsesAvatarScaleModel {
	this := RobloxWebResponsesAvatarScaleModel{}
	return &this
}

// NewRobloxWebResponsesAvatarScaleModelWithDefaults instantiates a new RobloxWebResponsesAvatarScaleModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRobloxWebResponsesAvatarScaleModelWithDefaults() *RobloxWebResponsesAvatarScaleModel {
	this := RobloxWebResponsesAvatarScaleModel{}
	return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetHeight() float64 {
	if o == nil || IsNil(o.Height) {
		var ret float64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetHeightOk() (*float64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given float64 and assigns it to the Height field.
func (o *RobloxWebResponsesAvatarScaleModel) SetHeight(v float64) {
	o.Height = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetWidth() float64 {
	if o == nil || IsNil(o.Width) {
		var ret float64
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetWidthOk() (*float64, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given float64 and assigns it to the Width field.
func (o *RobloxWebResponsesAvatarScaleModel) SetWidth(v float64) {
	o.Width = &v
}

// GetHead returns the Head field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetHead() float64 {
	if o == nil || IsNil(o.Head) {
		var ret float64
		return ret
	}
	return *o.Head
}

// GetHeadOk returns a tuple with the Head field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetHeadOk() (*float64, bool) {
	if o == nil || IsNil(o.Head) {
		return nil, false
	}
	return o.Head, true
}

// HasHead returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasHead() bool {
	if o != nil && !IsNil(o.Head) {
		return true
	}

	return false
}

// SetHead gets a reference to the given float64 and assigns it to the Head field.
func (o *RobloxWebResponsesAvatarScaleModel) SetHead(v float64) {
	o.Head = &v
}

// GetDepth returns the Depth field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetDepth() float64 {
	if o == nil || IsNil(o.Depth) {
		var ret float64
		return ret
	}
	return *o.Depth
}

// GetDepthOk returns a tuple with the Depth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetDepthOk() (*float64, bool) {
	if o == nil || IsNil(o.Depth) {
		return nil, false
	}
	return o.Depth, true
}

// HasDepth returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasDepth() bool {
	if o != nil && !IsNil(o.Depth) {
		return true
	}

	return false
}

// SetDepth gets a reference to the given float64 and assigns it to the Depth field.
func (o *RobloxWebResponsesAvatarScaleModel) SetDepth(v float64) {
	o.Depth = &v
}

// GetProportion returns the Proportion field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetProportion() float64 {
	if o == nil || IsNil(o.Proportion) {
		var ret float64
		return ret
	}
	return *o.Proportion
}

// GetProportionOk returns a tuple with the Proportion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetProportionOk() (*float64, bool) {
	if o == nil || IsNil(o.Proportion) {
		return nil, false
	}
	return o.Proportion, true
}

// HasProportion returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasProportion() bool {
	if o != nil && !IsNil(o.Proportion) {
		return true
	}

	return false
}

// SetProportion gets a reference to the given float64 and assigns it to the Proportion field.
func (o *RobloxWebResponsesAvatarScaleModel) SetProportion(v float64) {
	o.Proportion = &v
}

// GetBodyType returns the BodyType field value if set, zero value otherwise.
func (o *RobloxWebResponsesAvatarScaleModel) GetBodyType() float64 {
	if o == nil || IsNil(o.BodyType) {
		var ret float64
		return ret
	}
	return *o.BodyType
}

// GetBodyTypeOk returns a tuple with the BodyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RobloxWebResponsesAvatarScaleModel) GetBodyTypeOk() (*float64, bool) {
	if o == nil || IsNil(o.BodyType) {
		return nil, false
	}
	return o.BodyType, true
}

// HasBodyType returns a boolean if a field has been set.
func (o *RobloxWebResponsesAvatarScaleModel) HasBodyType() bool {
	if o != nil && !IsNil(o.BodyType) {
		return true
	}

	return false
}

// SetBodyType gets a reference to the given float64 and assigns it to the BodyType field.
func (o *RobloxWebResponsesAvatarScaleModel) SetBodyType(v float64) {
	o.BodyType = &v
}

func (o RobloxWebResponsesAvatarScaleModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RobloxWebResponsesAvatarScaleModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Head) {
		toSerialize["head"] = o.Head
	}
	if !IsNil(o.Depth) {
		toSerialize["depth"] = o.Depth
	}
	if !IsNil(o.Proportion) {
		toSerialize["proportion"] = o.Proportion
	}
	if !IsNil(o.BodyType) {
		toSerialize["bodyType"] = o.BodyType
	}
	return toSerialize, nil
}

type NullableRobloxWebResponsesAvatarScaleModel struct {
	value *RobloxWebResponsesAvatarScaleModel
	isSet bool
}

func (v NullableRobloxWebResponsesAvatarScaleModel) Get() *RobloxWebResponsesAvatarScaleModel {
	return v.value
}

func (v *NullableRobloxWebResponsesAvatarScaleModel) Set(val *RobloxWebResponsesAvatarScaleModel) {
	v.value = val
	v.isSet = true
}

func (v NullableRobloxWebResponsesAvatarScaleModel) IsSet() bool {
	return v.isSet
}

func (v *NullableRobloxWebResponsesAvatarScaleModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRobloxWebResponsesAvatarScaleModel(val *RobloxWebResponsesAvatarScaleModel) *NullableRobloxWebResponsesAvatarScaleModel {
	return &NullableRobloxWebResponsesAvatarScaleModel{value: val, isSet: true}
}

func (v NullableRobloxWebResponsesAvatarScaleModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRobloxWebResponsesAvatarScaleModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


