package flags

func applyEnvironmentVariableFlags() {
	getEnvironmentVariableOrFlag("BIND_ADDRESS_IPv4", BindAddressIpv4)

	getEnvironmentVariableOrFlag("VAULT_ADDR", VaultAddress)
	getEnvironmentVariableOrFlag("VAULT_CREDENTIAL", VaultCredential)
	getEnvironmentVariableOrFlag("VAULT_AUTHENTICATION_TYPE", VaultAuthenticationType)
	getEnvironmentVariableOrFlag("VAULT_NAMESPACE", VaultNamespace)
	getEnvironmentVariableOrFlag("VAULT_SKIP_TLS_VERIFY", VaultSkipTlsVerify)

	getEnvironmentVariableOrFlag("CLIENT_SETTINGS_VAULT_MOUNT_PATH", ClientSettingsVaultMountPath)
	getEnvironmentVariableOrFlag("CLIENT_SETTINGS_VAULT_PATH", ClientSettingsVaultPath)
	getEnvironmentVariableOrFlag("CLIENT_SETTINGS_PROVIDER_REFRESH_INTERVAL", ClientSettingsProviderRefreshInterval)
	getEnvironmentVariableOrFlag("CLIENT_SETTINGS_API_KEYS", ClientSettingsApiKeys)

	getEnvironmentVariableOrFlag("AVATAR_API_URL", AvatarApiUrl)
	getEnvironmentVariableOrFlag("AVATAR_FETCH_CACHE_INVALIDATION_INTERVAL", AvatarFetchCacheInvalidationInterval)
	getEnvironmentVariableOrFlag("AVATAR_FETCH_CACHE_ITEM_EXPIRATION", AvatarFetchCacheItemExpiration)

	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_REPORTING_ENABLED", EphemeralCountersInfluxDbReportingEnabled)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_MAX_BATCH_SIZE", EphemeralCountersInfluxDbMaxBatchSize)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_FLUSH_INTERVAL", EphemeralCountersInfluxDbFlushInterval)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_REPORTING_URL", EphemeralCountersInfluxDbReportingUrl)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_REPORTING_DATABASE", EphemeralCountersInfluxDbReportingDatabase)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_REPORTING_TOKEN", EphemeralCountersInfluxDbReportingToken)
	getEnvironmentVariableOrFlag("EPHEMERAL_COUNTERS_INFLUXDB_REPORTING_ORGANIZATION", EphemeralCountersInfluxDbReportingOrganization)
}
